#!/usr/bin/env bash
set -euo pipefail

# Runs the same quality checks as the riff-quality CI workflow.
# Usage: ./scripts/check-quality.sh

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FAILED=0

echo "=== Rustfmt ==="
# config.rs is generated by meson; create an empty placeholder if missing.
if [[ ! -f "$REPO_ROOT/src/config.rs" ]]; then
    echo "(creating empty src/config.rs placeholder)"
    echo > "$REPO_ROOT/src/config.rs"
fi

if cargo fmt --all -- --check; then
    echo "PASS"
else
    echo "FAIL — run 'cargo fmt --all' to fix."
    FAILED=1
fi

echo ""
echo "=== ShellCheck ==="
if ! command -v shellcheck &>/dev/null; then
    echo "shellcheck not found — install it to run this check."
    FAILED=1
else
    SHELL_FILES=$(find "$REPO_ROOT" -type f -name "*.sh" \
        -not -path "*/cargo/*" \
        -not -path "*/target/*")

    if [[ -z "$SHELL_FILES" ]]; then
        echo "No .sh files found."
    else
        # shellcheck disable=SC2086
        if shellcheck $SHELL_FILES; then
            echo "PASS"
        else
            echo "FAIL"
            FAILED=1
        fi
    fi
fi

echo ""
if [[ "$FAILED" -ne 0 ]]; then
    echo "Quality checks failed."
    exit 1
else
    echo "All quality checks passed."
fi
